/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/* eslint-disable react/prop-types */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 developer.glb -T 
Files: developer.glb [981.62KB] > Z:\WORKS\PORTFOLIO\vite-react\portfolio-vite\public\models\animations\developer-clap.fbx [395.08KB] (60%)
*/
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Developer = ({ animationName = "idle", ...props }) => {
  return;
};

export default Developer;
